name: Generate Excel Sheet

on:
  pull_request:
    types: [closed]

jobs:
  generate-excel:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install openpyxl

      - name: Generate Excel sheet
        run: |
          python generate_excel.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT: ${{ github.event }}

      - name: Upload Excel sheet
        uses: actions/upload-artifact@v2
        with:
          name: excel-sheet.xlsx
          path: excel-sheet.xlsx
