name: Generate Excel Sheet

on:
  pull_request:
    types: [closed]
permissions:
  contents: write  
  
jobs:
  generate-excel:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install dependencies
        run: pip install openpyxl

      - name: log PR info
        run: python .github/scripts/log_pr.py

      - name: Commit and push excel file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config push.default matching
          git add pull_requests.xlsx
          git commit -m "Update PR log from #${{ github.event.pull_request.number }}" || echo "No changes to commit"          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
